package org.omg.IOP;


/**
* org/omg/IOP/TAG_CODE_SETS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/cygwin64/tmp/ojdkbuild/lookaside/java-1.8.0-openjdk/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Saturday, May 1, 2021 10:50:01 PM PDT
*/

public interface TAG_CODE_SETS
{

  /**
     * The code set component of the IOR multi-component profile structure
     * contains:
     * <ul>
     *   <li>server's native char code set and conversion code sets, and</li>
     *   <li>server's native wchar code set and conversion code sets.</li>
     * </ul>
     * Both char and wchar conversion code sets are listed in order of 
     * preference.
     */
  public static final int value = (int)(1L);
}
